# Generated by Django 5.2.7 on 2025-11-05 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_dressed_app', '0002_wardrobeitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Summer Date Night', 'Office Monday'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Describe the outfit and when to wear it', max_length=1000)),
                ('occasion', models.CharField(blank=True, choices=[('casual', 'Casual'), ('business', 'Business/Professional'), ('formal', 'Formal'), ('athletic', 'Athletic/Workout'), ('night_out', 'Night Out'), ('date', 'Date'), ('other', 'Other')], help_text='What type of occasion is this outfit for?', max_length=50)),
                ('season', models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter'), ('all', 'All Seasons')], help_text='What season is this outfit best for?', max_length=50)),
                ('is_favorite', models.BooleanField(default=False, help_text='Mark as a favorite outfit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(blank=True, help_text='Items included in this outfit', related_name='outfits', to='best_dressed_app.wardrobeitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_favorite', '-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
