# Generated by Django 5.2.7 on 2025-11-15 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_dressed_app', '0003_outfit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text="User's request for recommendations", max_length=1000)),
                ('ai_response', models.TextField(help_text='AI-generated fashion recommendations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_items', models.ManyToManyField(blank=True, help_text='Catalog items that were recommended to the user', related_name='recommendations', to='best_dressed_app.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
