# Generated by Django 5.2.7 on 2025-12-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_dressed_app', '0006_auto_20251205_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('dress', 'Dress'), ('outerwear', 'Outerwear'), ('shoes', 'Shoes'), ('accessory', 'Accessory'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
