# Generated by Django 5.2.7 on 2025-11-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_thread_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='thread',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
