# Generated by Django 5.2.7 on 2025-12-03 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_dressed_app', '0005_item_item_ebay_url_item_item_id_item_seller_id_and_more'),
        ('forum', '0005_savedthread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='attached_outfit',
            field=models.ForeignKey(blank=True, help_text='Optional outfit to attach to this thread', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_threads', to='best_dressed_app.outfit'),
        ),
    ]
