name: Python Tests + Linting

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: Build databases
        run: |
            python manage.py makemigrations
            python manage.py migrate
      - name: Test with django
        run: |
            coverage run manage.py test
        continue-on-error: true
      - name: Show coverage report
        run: |
            coverage report
      - name: Analysing the code with pylint
        run: |
            pylint best_dressed/. || true
            pylint best_dressed_app/. || true